### ISSUE TITLE
Your Steamlit Crashed 

### ISSUE THREAD

**Issue by Christoway** [aju22/DocumentGPT#1]
Hello, 

Your Streamlit Crashed. Can you fix this?

**Comment by aju22** [comment]
Yes the cloud app did seem to have crashed. I have rebooted the app. Seems to be fine now.

**Comment by Christoway** [comment]
Thank you.

**Comment by Christoway** [comment]
It crashed again. https://documentgpt.streamlit.app/

Can you try moving it to huggingface? It's more stable.
