### ISSUE TITLE
No Secret Files Found Error 

### ISSUE THREAD

**Issue by Christoway** [aju22/DocumentGPT#2]
I get this Error when running the program. How can I fix this?

![Screenshot_6](https://github.com/aju22/DocumentGPT/assets/28645433/6e1104cc-fd83-49bb-84f8-3f11f8353a58)

**Comment by aju22** [comment]
Yes it's pretty straightforward. Create a Directory named .streamlit inside which you have to create a secrets.toml file.
Now go to [SerpAPI](https://serpapi.com/) and register yourself to obtain an API key, this is used for the web search tool in this app.
Paste this API key into the secrets.toml file as:

```
serp_api_key = ....your_key
```

**Comment by dustin2551** [comment]
It didn't work.
